services:
  - type: web
    name: olympic-django
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Project_olympic_main.wsgi:application
